name: "Bug report"
description: Report a problem in QuiGenie
title: "fix: "
labels: ["bug"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      placeholder: e.g., Cannot submit answer on second question
    validations:
      required: true
  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      placeholder: |
        1. Go to ...
        2. Click ...
        3. See error ...
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: Expected behavior
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: Actual behavior
    validations:
      required: true
  - type: textarea
    id: env
    attributes:
      label: Environment
      placeholder: OS, browser, version, etc.
