name: "Feature request"
description: Propose a new capability for QuiGenie
title: "feat: "
labels: ["feature"]
body:
  - type: input
    id: summary
    attributes:
      label: Summary
      description: One-line summary of the feature
      placeholder: e.g., Allow creators to schedule quizzes
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Details
      description: What problem does this solve? What is the value?
    validations:
      required: true
  - type: textarea
    id: acceptance
    attributes:
      label: Acceptance Criteria
      description: Bullet points for done conditions
      placeholder: |
        - Given X, when Y, then Z
  - type: input
    id: scope
    attributes:
      label: Branch name suggestion
      description: feat/<scope>-<desc>
